```{r data generation, echo = FALSE, results = "hide"}
library(knitr)
library(dplyr)
library(kableExtra)

## Generación de datos
tipo <- sample(1:3, 1)

## Tipo 1. Relativo a filas ############
# La función p crea un vector con tres frecuencias aleatorias que suman 1

p <- function(){
    p1 <- runif(1, 0.2, 0.7)
    p2 <- runif(1, 0.2, 0.9-p1)
    p3 <- 1 - p1 - p2
    
    c(p1, p2, p3)
}


if(tipo == 1){
    mat <- matrix(c(p(), p(), p()), 3, byrow = FALSE)
    mat <- cbind(mat, p())
    mat <- addmargins(mat, 1)
}

if(tipo == 2){
    mat <- matrix(c(p(), p(), p()), 3, byrow = TRUE)
    mat <- rbind(mat, p())
    mat <- addmargins(mat, 2)
}

if(tipo == 3){
    mat <- matrix(runif(9), 3, byrow = TRUE)
    mat <- prop.table(mat)
    mat <- addmargins(mat)
}

## Creamos la matriz de datos
# mat <- matrix(c(p(), p(), p()), 3, byrow = FALSE)

## Agregamos las frecuencias marginales
# mat <- cbind(mat, p())
# mat <- addmargins(mat, 1)

## Agregamos los nombres de variables y dimensiones
dimnames(mat) <- list("Tipo de organización en la que trabaja"  =  c("Estatal", "Privada", "ONG", "Total"),
                      "Grado de satisfacción laboral" = c("Muy satisfecho", "Satisfecho", "Poco satisfecho", "Total"))


## Convertimos a porcentajes
mat <- mat * 100

## Generamos un valor aleatorio para la pregunta
i <- sample(1:3, 1)
j <- sample(1:3, 1)

mat[i,j]

organizacion <- switch(i,
                       "1" = "organizaciones estatales",
                       "2" = "organizaciones privadas",
                       "3" = "ONGs")

satisfaccion <- switch(j,
                       "1" = "muy satisfechos",
                       "2" = "satisfechos",
                       "3" = "poco satisfechos")

## Opciones
opciones <- c("1" = paste("El ", round(mat[i, j], 2), "% de los que están ", satisfaccion, " trabajan en ", organizacion, ".", sep = ""),
              "2" = paste("El ", round(mat[i, j], 2), "% de los que trabajan en ", organizacion, " están ", satisfaccion, ".", sep = ""),
              "3" = paste("El ", round(mat[i, j], 2), "% trabajan en ", organizacion, " y están ", satisfaccion, ".", sep = ""),
              "4" = paste("El ", round(mat[i, j], 2), "% trabajan en ", organizacion, " o están ", satisfaccion, ".", sep = "")
)

## Caption
caption <- c("porcentaje por **tipo de organización** relativo al grado de **satisfacción laboral**.",
             "porcentaje relativo al **tipo de organización**, por grado de **satisfacción laboral**.",
             "porcentaje para **tipo de organización** y **satisfacción laboral**.")

incorrectas <- which(!names(opciones) == tipo)
correcta <- which(names(opciones) == tipo)

## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)

questions[1] <- opciones[correcta]
solutions[1] <- TRUE

questions[2] <- opciones[incorrectas[1]]
solutions[2] <- FALSE
    
questions[3] <- opciones[incorrectas[2]]
solutions[3] <- FALSE

questions[4] <- opciones[incorrectas[3]]
solutions[4] <- FALSE
```

Question
========
**R2018_0015**. En un estudio determinado se quiso estudiar la relación entre el grado de satisfacción laboral y el tipo de organización. La siguiente tabla representa el `r caption[tipo]` Seleccione la afirmación correcta para la siguiente Tabla.

<!-- \captionsetup[table]{name = Tabla} -->
```{r frecuenciaRelativayAbsoluta, echo = FALSE}
# options(kableExtra.latex.load_packages = FALSE)
kable(mat, digits = 2,
      booktabs = TRUE,
      format = "latex",
      # caption = "",
      longtable = TRUE) %>%
    kable_styling(latex_options = "hold_position") %>%
    # column_spec(1, width = "4cm") %>%
    add_header_above(c(" " = 1, "Grado de Satisfacción" = 3, " " = 1)) %>%
    group_rows("Tipo de Organización", 1, 3, label_row_css = NULL)
```  
  
  

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```
  
Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(solutions, markup = "markdown")
```

Meta-information
================
exname: R2018_0015L
extype: schoice
exsolution: 1000
exshuffle: TRUE