```{r data generation, echo = FALSE, results = "hide"}
## convenience functions
SK <- function(x) diff(diff(fivenum(x)[2:4]))/diff(fivenum(x)[c(2, 4)])
trob <- function(a, b)
  (median(a) - median(b))/sqrt(var(a)/length(a) + var(b)/length(b))

## DATA GENERATION
## dgp for one sample
dgp <- function(location = 0, scale = 1, skewed = FALSE, outlier = NULL,
  n = 10, amount = 0.1)
{
  ## basic intervals from which equal amounts of observations are drawn
  qq <- if (skewed) c(0, 2, 2.2, 6, 10) else c(0, 3, 5, 7, 10)
  sim <- function(x) {
    rval <- NULL
    for(i in 1:(length(x)-1)) rval <- c(rval, runif(n, min = x[i], max = x[i+1]))
    rval <- jitter(rval, amount = amount)
    rval <- rval/4
    rval
  }
  ## draw under restrictions about IQR and SK
  rval <- sim(qq)
  if (skewed) {
    while(IQR(rval) > 1.15 | IQR(rval) < 0.85 | abs(SK(rval)) < 0.7) rval <- sim(qq)
  } else {
    while(IQR(rval) > 1.15 | IQR(rval) < 0.85 |abs(SK(rval)) > 0.15) rval <- sim(qq)
  }

  ## raw values (location = 0, scale = 1)
  rval <- rval - ifelse(skewed, 0.55, 1.25)

  ## add outliers
  rval <- c(rval, outlier)
  
  ## scale and shift
  rval <- rval * scale + location

  return(rval)
}

## generate random parameters for dgp()
scale <- sample(c(1, sample(c(1, 3), 1))) * runif(1, min = 0.5, max = 10) * sample(c(-1, 1), 1)
location <- sample(c(0, sample(c(0, 2), 1))) * scale + runif(1, min = -50, max = 50)
skewed <- if (runif(1) < 2/3) c(FALSE, FALSE) else sample(c(TRUE, sample(c(TRUE, FALSE), 1)))
if (runif(1) < 2/3) {
  outlier <- list(NULL, NULL)
} else {
  if (any(skewed)) {
    outlier <- if (skewed[1]) -sign(scale[1]) * runif(sample(1:2, 1), min = 3, max = 4) else NULL
    outlier <- c(list(outlier), if (skewed[2])
      list(-sign(scale[1]) * runif(sample((0:1 + !skewed[1]), 1), min = 3, max = 4)) else list(NULL))
  } else {
    outlier <- runif(sample(1:3, 1), min = 3, max = 4)
    outlier <- outlier * sample(c(-1, 1), length(outlier), replace = TRUE)
    id <- sample(1:length(outlier), sample(1:length(outlier), 1))
    outlier1 <- outlier[id]
    outlier2 <- outlier[-id]
    outlier <- list(if(length(outlier1) > 0) outlier1 else NULL,
      if (length(outlier2) > 0) outlier2 else NULL)
  }
}

## call dgp under certain constrains
A <- dgp(location = location[1], scale = scale[1], skewed = skewed[1], outlier = outlier[[1]],
  n = sample(8:12, 1))
B <- dgp(location = location[2], scale = scale[2], skewed = skewed[2], outlier = outlier[[2]],
  n = sample(8:12, 1))
while((length(unique(location)) < 2 & abs(trob(A, B)) > 0.4) | (abs(SK(A)) > 0.15 & abs(SK(A)) < 0.7) | (abs(SK(B)) > 0.15 & abs(SK(B)) < 0.7)) {
  A <- dgp(location = location[1], scale = scale[1], skewed = skewed[1], outlier = outlier[[1]],
    n = sample(8:12, 1))
  B <- dgp(location = location[2], scale = scale[2], skewed = skewed[2], outlier = outlier[[2]],
    n = sample(8:12, 1))
}
SK_A <- ifelse(abs(SK(A)) < 0.2, "simétrica", ifelse(SK(A) >= 0.2, "asimétrica a la derecha", "asimétrica a la izquierda"))
SK_B <- ifelse(abs(SK(B)) < 0.2, "simétrica", ifelse(SK(B) >= 0.2, "asimétrica a la derecha", "asimétrica a la izquierda"))

## QUESTION/ANSWER GENERATION
questions <- character(5)
solutions <- logical(5)
explanations <- character(5)
texto <- vector("list", 5)
opcioncorrecta <- logical(5)

## Determino cual va a ser la opción correcta
opcioncorrecta[sample(1:5, 1)] <- TRUE

## Convertimos las preguntas en schoice
texto[[c(1,1)]] <- "La ubicación de ambas distribuciones es aproximadamente la misma"
texto[[c(1,2)]] <- "La ubicación de ambas distribuciones es notablemente diferente"

# solutions[1] <- abs(trob(A, B)) < 0.5

questions[1] <- if(opcioncorrecta[1]){
    ifelse(abs(trob(A, B)) < 0.5, texto[[c(1,1)]], texto[[c(1,2)]])
} else {
        ifelse(!(abs(trob(A, B)) < 0.5), texto[[c(1,1)]], texto[[c(1,2)]])
}

solutions[1] <- opcioncorrecta[1]
# explanations[1] <- if (solutions[1]) "Ambas distribuciones tienen una ubicación similar" else
#   paste("La distribución ", c("A", "B")[(median(A) < median(B)) + 1],
#     " tiene en promedio, valores mayores que la distribución ",
#     c("A", "B")[(median(A) >= median(B)) + 1], ".", sep = "")


texto[[c(2,1)]] <- "Ninguna distribución contiene valores extremos"
texto[[c(2,2)]] <- "Al menos una de las distribuciones contiene valores extremos"

outlier <- length(unlist(outlier)) > 0
questions[2] <- if(opcioncorrecta[2]){
    ifelse(!outlier, texto[[c(2,1)]], texto[[c(2,2)]])
} else {
        ifelse(outlier, texto[[c(2,1)]], texto[[c(2,2)]])
}
# questions[2] <- "Ninguna distribución contiene valores extremos"

solutions[2] <- opcioncorrecta[2]

# solutions[2] <- !outlier
# explanations[2] <- if (solutions[2])
#   "Ninguna de las dos distribuciones contiene observaciones que se desvíen más de 1,5 veces el rango intercuartílico de la caja." else "Hay observaciones que se desvían más de 1,5 veces el rango intercuartílica de la mediana."

texto[[c(3,1)]] <- "La dispersión en la muestra A es claramente mayor que en la muestra B."
texto[[c(3,2)]] <- "La dispersión en la muestra A es menor o igual que en la muestra B."

# questions[3] <- "La dispersión en la muestra A es claramente mayor que en la muestra B."
questions[3] <- if(opcioncorrecta[3]){
    ifelse(IQR(A)/IQR(B) > 1.5, texto[[c(3,1)]], texto[[c(3,2)]])
} else {
        ifelse(!(IQR(A)/IQR(B) > 1.5), texto[[c(3,1)]], texto[[c(3,2)]])
}
# solutions[3] <- IQR(A)/IQR(B) > 1.5
solutions[3] <- opcioncorrecta[3]

# explanations[3] <- paste("El rango intercuartílico en la muestra A ", ifelse(solutions[3], "", "no"), "es claramente mayor que en B.")

texto[[c(4,1)]] <- "La simetría de ambas muestras es similar."
texto[[c(4,2)]] <- "La simetría de ambas muestras es diferente."

# questions[4] <- "La simetría de ambas muestras es similar."

questions[4] <- if(opcioncorrecta[4]){
    ifelse(SK_A == SK_B, texto[[c(4,1)]], texto[[c(4,2)]])
} else {
        ifelse(!(SK_A == SK_B), texto[[c(4,1)]], texto[[c(4,2)]])
}

# solutions[4] <- SK_A == SK_B
solutions[4] <- opcioncorrecta[4]

# explanations[4] <- if (solutions[4]) paste("La simetría de ambas distribuciones es similar. Ambas son ",
#     ifelse(abs(SK(A)) < 0.2, "aproximadamente simétricas.", ifelse(SK(A) >= 0.2, "asimétricas a la derecha.", "asimétricas a la izquierda."))) else
#     paste("La simetría de ambas distribuciones es diferente. La muestra A es ",
#     ifelse(abs(SK(A)) < 0.2, "aproximadamente simétrica.", ifelse(SK(A) >= 0.2, "asimétrica a la derecha.", "asimétrica a la izquierda.")),
#     "La muestra B es", ifelse(abs(SK(B)) < 0.2, "Aproximadamente simétrica.", ifelse(SK(B) >= 0.2, "asimétrica a la derecha", "asimétrica a la izquierda.")))

i <- sample(1:2, 1)
j <- sample(1:3, 1)

texto[[c(5,1)]] <- paste("La distribución ", c("A", "B")[i], " es ", 
                      c("aproximadamente simétrica", "asimétrica a la derecha", "asimétrica a la izquierda")[j], ".", sep = "")
texto[[c(5,2)]] <- paste("La distribución ", c("A", "B")[i], " es ", 
                      c("asimétrica a la derecha", "asimétrica a la izquierda", "aproximadamente simétrica")[j], ".", sep = "")

SK_i <- SK(list(A, B)[[i]])
questions[5] <- if(opcioncorrecta[5]){
    ifelse(switch(j, abs(SK_i) < 0.2,
                       SK_i >= 0.2,
                       SK_i <= -0.2), texto[[c(5,1)]], texto[[c(5,2)]])
} else {
        ifelse(!switch(j, abs(SK_i) < 0.2,
                       SK_i >= 0.2,
                       SK_i <= -0.2), texto[[c(5,1)]], texto[[c(5,2)]])
}

# questions[5] <- paste("La distribución ", c("A", "B")[i], " es ", 
#                       c("aproximadamente simétrica", "asimétrica a la derecha", "asimétrica a la izquierda")[j], ".", sep = "")



solutions[5] <- opcioncorrecta[5]

# solutions[5] <- switch(j, abs(SK_i) < 0.2,
#                        SK_i >= 0.2,
#                        SK_i <= -0.2)
# explanations[5] <- paste("La distribución ", c("A", "B")[i], " es ",
#                          ifelse(abs(SK_i) < 0.2, "aproximadamente simétrica.", 
#                                 ifelse(SK_i >= 0.2, "asimétrica a la derecha.", "asimétrica a la izquierda.")))
```

Question
========
En la siguiente figura, la distribución de una variable,
dada en dos muestras (A y B) son representados por dos boxplots paralelos.
¿Cuál de los siguientes postulados es correcto?.  
  
\
```{r boxplot, echo = FALSE, results = "hide", fig.height = 4, fig.width = 5, fig.path = "", fig.cap = ""}
par(mar = c(2.5, 2, 1, 0.5))
dat <- data.frame(y = c(A, B), x = factor(rep(c("A", "B"), c(length(A), length(B)))))
boxplot(y ~ x, data = dat, xlab = "", ylab = "")
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```


Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(opcioncorrecta, markup = "markdown")
```

Meta-information
================
extype: schoice
exname: Parallel boxplots
exsolution: `r paste(as.numeric(opcioncorrecta), collapse = "")`
exshuffle: 4