```{r data generation, echo = FALSE, results = "hide"}
library(kableExtra)

## Generación de datos
x1 <- round(runif(1, 5, 150), 2) ## Media bajo H0
x2 <- round(runif(1, 30, 200)) ## n
x3 <- round(runif(1, -3.5, 3.5), 2) ## T
x5 <- round(2 * (1 - pt(abs(x3), x2 - 1)), 4) ## p
x6 <- round(0.1 * x1, 2) ## DE
x4 <- round(x1 + x3 * x6/sqrt(x2), 2) ## media estimada

## Construimos la tabla

df <- data.frame(n = x2, Media = x4, DE = x6, T = x3, `p(Bilateral)` = paste(ifelse(x5 < .00001, "< 0.0001", paste(format(x5, scientific = FALSE)))))


## Sorteamos un tipo de pregunta
correctas <- c(paste("El estimador puntual es ", x4, ".", sep = ""),
              paste("Si Ho fuera verdadera, la probabilidad de hallar un valor del estimador como el observado o más extremo es ", x5, ".", sep = ""),
              paste("El estimador está a ", abs(x3), " desviaciones estándar de ", x1, ".", sep = ""),
              paste("El parámetro hipotético es ", x1, ".", sep = ""),
              paste("A un nivel del 5% corresponde ", ifelse(x5 < 0.5, "rechazar ", "no rechazar"), " la hipótesis nula.", sep = ""),
              paste("A un nivel del 1% corresponde ", ifelse(x5 < 0.1, "rechazar ", "no rechazar"), " la hipótesis nula.", sep = ""))


incorrectas <- c(paste("El estimador puntual es ", x1, ".", sep = ""),
                 paste("El estimador puntual es ", x6, ".", sep = ""),
                 paste("Si Ho fuera verdadera, la probabilidad de hallar un valor del estimador como el observado o más extremo es ", x1, ".", sep = ""),
                 paste("El estimador está a ", x5, " desviaciones estándar de ", x1, ".", sep = ""),
                 paste("El estimador está a ", ".1", " desviaciones estándar de ", x1, ".", sep = ""),
                 paste("El parámetro hipotético es ", x4, ".", sep = ""),
                 paste("Si Ho fuera falsa, la probabilidad de hallar un valor del estimador como el observado o más extremo es ", x5, ".", sep = ""),
                 paste("A un nivel del 5% corresponde ", ifelse(x5 > 0.5, "rechazar ", "no rechazar"), "la hipótesis nula.", sep = ""),
                 paste("A un nivel del 1% corresponde ", ifelse(x5 > 0.1, "rechazar ", "no rechazar"), "la hipótesis nula.", sep = ""))



opciones <- c(sample(correctas, 1), sample(incorrectas, 3))

## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)

questions[1] <- opciones[1]
solutions[1] <- TRUE

questions[2] <- opciones[2]
solutions[2] <- FALSE
    
questions[3] <- opciones[3]
solutions[3] <- FALSE

questions[4] <- opciones[4]
solutions[4] <- FALSE
```
Question
========
**R2018_0030**. Dado el siguiente resultado:

```
Prueba t para una media

Valor de la media bajo la hipótesis nula: `r x1`
```

```{r tabla2018_0030, echo = FALSE, comment = NA}
kable(df) %>% 
    kable_styling(bootstrap_options = c("striped", "hover"))
```  


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```
  
Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(solutions, markup = "markdown")
```

Meta-information
================
exname: R2018_0030
extype: schoice
exsolution: 1000
exshuffle: TRUE