```{r data generation, echo = FALSE, results = "hide"}
## Generación de datos
x <- sample(1:100, 1)
xzx <- sample(50:5000, 1)

## Opciones
opciones <- c(paste("El", x, "% de los sujetos obtuvo puntajes por debajo de", xzx),
              paste("El", x, "% de los sujetos obtuvo puntajes por encima de", xzx),
            paste("El", (100 - x), "% de los sujetos obtuvo puntajes por debajo de", xzx),
                paste("El", x, "% de los sujetos obtuvo puntajes iguales a", xzx))

# incorrectas <- which(!names(opciones) == cat)
# correcta <- which(names(opciones) == cat)
## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)

questions[1] <- opciones[1]
solutions[1] <- TRUE

questions[2] <- opciones[2]
solutions[2] <- FALSE
    
questions[3] <- opciones[3]
solutions[3] <- FALSE

questions[4] <- opciones[4]
solutions[4] <- FALSE
```

Question
========
**R2018_0009**. Si el percentil `r x` de los puntajes de una prueba es `r xzx`, entonces:  


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```
  
Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(solutions, markup = "markdown")
```

Meta-information
================
exname: R2018_0009
extype: schoice
exsolution: 1000
exshuffle: TRUE