```{r data generation, echo = FALSE, results = "hide"}
library(dplyr)
library(ggplot2)


## Generación de datos
A <- sample(1:20, 5)
B <- sample(1:20, 5)

qA <- quantile(A)
qB<- quantile(B)

## Sorteamos un tipo de pregunta
df <- data.frame(x = c("A", "B"),
                 min = c(qA[1], qB[1]),
                 low = c(qA[2], qB[2]),
                 mid = c(qA[3], qB[3]),
                 top = c(qA[4], qB[4]),
                 max = c(qA[5], qB[5]))

gg <- ggplot(df, aes(x = x,
                     ymin = min,
                     lower = low,
                     middle = mid,
                     upper = top,
                     ymax = max)) +
    geom_boxplot(stat = "identity") +
    scale_y_continuous(breaks=seq(2,20, by = 2)) +
    theme_bw() +
    xlab(NULL)


## Creamos un data.frame para poder identificar las respuestas incorrectas
grupo <- sample(0:1, 1) ## 0 es igual al grupo A

preguntas <- c("el recorrido", "el recorrido intercuartílico", "el semi recorrido intercuartilar")

if(grupo == 0){
    correctas <- c(qA[5] - qA[1], qA[4] - qA[2], (qA[4] - qA[2])/2)
} else {
    correctas <- c(qB[5] - qB[1], qB[4] - qB[2], (qB[4] - qB[2])/2)
}


dfpreguntas <- data.frame(id = 1:3, preguntas = preguntas, correctas = correctas, stringsAsFactors = FALSE)

## Aleatorizamos el tipo de pregunta (si es mínimo, cuartil, mediana, ...)
i <- sample(1:3, 1)

## Elegimos las respuestas incorrectas
incorrectas <- c(dfpreguntas$correctas[dfpreguntas$id != i],
                 dfpreguntas$correctas[i] - 2)


## Elegimos un tipo de pregunta
opciones <- as.character(c(correctas[i], incorrectas))

## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)

questions[1] <- opciones[1]
solutions[1] <- TRUE

questions[2] <- opciones[2]
solutions[2] <- FALSE
    
questions[3] <- opciones[3]
solutions[3] <- FALSE

questions[4] <- opciones[4]
solutions[4] <- FALSE
```


Question
========
**R2018_0037**. En el siguiente gráfico de cajas, `r preguntas[i]` en el grupo `r ifelse(grupo == 0, "A", "B")` es:  


```{r boxplotR2018_0036, echo = FALSE, fig.height = 4, fig.path = "", fig.cap = ""}
gg
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```
  
  
Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(solutions, markup = "markdown")
```

Meta-information
================
exname: R2018_0037
extype: schoice
exsolution: 1000
exshuffle: TRUE