```{r data generation, echo = FALSE, results = "hide"}
## Generación de datos
cat <- sample(c("bajo", "intermedio", "alto", "nosepuede"), 1)
px <- switch (cat,
        "bajo" = runif(1, 0.01, 0.10),
        "intermedio" = runif(1, 0.45, 0.55),
        "alto" = runif(1, 0.80, 0.99),
        "nosepuede" = ifelse(
            sample(c(1,0), 1),
            runif(1, -0.99, -0.01),
            runif(1, 1.01, 1.05)
        )
)
    

## Opciones
opciones <- c(intermedio = "Moderada",
              alto = "Fuerte",
              bajo = "Débil",
              nosepuede = "Ha sido mal calculado")

incorrectas <- which(!names(opciones) == cat)
correcta <- which(names(opciones) == cat)

## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)

questions[1] <- opciones[correcta]
solutions[1] <- TRUE

questions[2] <- opciones[incorrectas[1]]
solutions[2] <- FALSE
    
questions[3] <- opciones[incorrectas[2]]
solutions[3] <- FALSE

questions[4] <- opciones[incorrectas[3]]
solutions[4] <- FALSE
```

Question
========
**R2018_0011**. Se la asociación entre dos variables da un coeficiente de Cramer V = `r round(px, 2)`, se trata de una relación:


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```
  
Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(solutions, markup = "markdown")
```

Meta-information
================
exname: R2018_0011
extype: schoice
exsolution: 1000
exshuffle: TRUE