```{r data generation, echo = FALSE, results = "hide"}
## Generación de datos
x <- round(runif(1, 11, 100), 2)
error <- round(runif(1, 5, 10), 2)
intervalo <- round(x + c(-1, 1) * error, 2)


df <- data.frame(codigo = 1:5,
                 concepto = c("el error", "la confianza", "el estimador puntual", "el límite inferior", "el límite superior"),
                 respuesta = c(paste(error), "No puede saberse con estos datos", paste(x), paste(x - error), paste (x + error)))

## Sorteamos un tipo de pregunta
tipo <- sample(1:5, 1)

pregunta <- as.character(df$concepto[df$codigo == tipo])
correcta <- as.character(df$respuesta[df$codigo == tipo])
incorrectas <- as.character(sample(df$respuesta[df$codigo != tipo], 3))

opciones <- c(correcta, incorrectas)

## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)

questions[1] <- opciones[1]
solutions[1] <- TRUE

questions[2] <- opciones[2]
solutions[2] <- FALSE
    
questions[3] <- opciones[3]
solutions[3] <- FALSE

questions[4] <- opciones[4]
solutions[4] <- FALSE
```
Question
========
**R2018_0028**. Para el intervalo que estima un media poblacional (`r intervalo[1]`, `r intervalo[2]`), `r pregunta` es:

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```
  
Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(solutions, markup = "markdown")
```

Meta-information
================
exname: R2018_0028
extype: schoice
exsolution: 1000
exshuffle: TRUE